# on:
#   push:
    # tags:
    #   - 'v*'
on: [push]

name: Release

jobs:
  build:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_files: wssocks-ustb-*
          - os: macos-latest
            artifact_files: |
              wssocks-ustb-client-macOS-amd64.app.zip
              client-ui-macOS-amd64.app.zip
          - os: windows-latest
            artifact_files: client-ui-windows-amd64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - run: go get fyne.io/fyne/v2/cmd/fyne   

      - name: Build Cli
        if: matrix.os == 'ubuntu-latest'
        run: |
          make

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: |
          cd client-ui
          make client-ui-macOS-amd64.app -f Makefile-ci
          zip -r client-ui-macOS-amd64.app.zip client-ui-macOS-amd64.app
          mv client-ui-macOS-amd64.app.zip ../
          cd ../
          echo "building swiftui-client"
          cd extra/go-api && ./build_archive.sh && cd ../../
          cd swiftui-client && xcodebuild -arch "x86_64"
          cd build/Release/ && zip -r wssocks-ustb-client-macOS-amd64.app.zip wssocks-ustb-client.app && cd ../../../
          mv swiftui-client/build/Release/wssocks-ustb-client-macOS-amd64.app.zip ./

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd client-ui
          make client-ui-windows-amd64.exe -f Makefile-ci
          cd ../
          mv client-ui/client-ui-windows-amd64.exe client-ui-windows-amd64.exe

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact-${{ matrix.os }}
          path: ${{ matrix.artifact_files }}

  release:
    name: On Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact-ubuntu-latest
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact-windows-latest
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact-macos-latest
      - run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            client-ui-windows-amd64.exe
            client-ui-macOS-amd64.app.zip
            wssocks-ustb-client-macOS-amd64.app.zip
            wssocks-ustb-darwin-amd64
            wssocks-ustb-linux-arm64
            wssocks-ustb-linux-amd64
            wssocks-ustb-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
